// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBriQWej-ib98MWCq0t8D3gCU8NpbuPjkk',
    appId: '1:1051521106036:web:0aced96151a06a88015121',
    messagingSenderId: '1051521106036',
    projectId: 'racket-sensor-db',
    authDomain: 'racket-sensor-db.firebaseapp.com',
    databaseURL: 'https://racket-sensor-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'racket-sensor-db.firebasestorage.app',
    measurementId: 'G-E1KJL15QGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmUbu6c8S4DHRzsAXmkS2g6sXd899PA80',
    appId: '1:1051521106036:android:2358d998f40924b0015121',
    messagingSenderId: '1051521106036',
    projectId: 'racket-sensor-db',
    databaseURL: 'https://racket-sensor-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'racket-sensor-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:1051521106036:ios:d072b950e135252e015121',
    messagingSenderId: '1051521106036',
    projectId: 'racket-sensor-db',
    databaseURL: 'https://racket-sensor-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'racket-sensor-db.firebasestorage.app',
    iosBundleId: 'com.example.smartracketApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFTxv71A3DiKxIdW_HnWhTjN8lOjurFhk',
    appId: '1:1051521106036:ios:d072b950e135252e015121',
    messagingSenderId: '1051521106036',
    projectId: 'racket-sensor-db',
    databaseURL: 'https://racket-sensor-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'racket-sensor-db.firebasestorage.app',
    iosBundleId: 'com.example.smartracketApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBriQWej-ib98MWCq0t8D3gCU8NpbuPjkk',
    appId: '1:1051521106036:web:ad3e80359e753ca7015121',
    messagingSenderId: '1051521106036',
    projectId: 'racket-sensor-db',
    authDomain: 'racket-sensor-db.firebaseapp.com',
    databaseURL: 'https://racket-sensor-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'racket-sensor-db.firebasestorage.app',
    measurementId: 'G-CWTYYNGZZR',
  );
}
